### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TomFaulkner** [TomFaulkner/News-At-Command-Line#5]
- [x] Move all files to proper locations (./news)
- [x] Move to plugins for news sources #6
- [x] Read config.yml from a default location #6, or ENV variable location
- [ ] Get rid of "websites_supported" in favor of using the classes #6 
- [ ] Finish PEP8ing
- [ ] Test all the things
- [ ] Update README (further updates)
- [ ] Read from environment variables + config + command line args
- [ ] Edit configuration in program
- [ ] Move all prompts to string constants file for easy changes and translations
- [ ] Dependency inject BeautifulSoup in extractor

## Someday maybe:
- [ ] Consider REST client / server architecture
